name: Build Employee Management Solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore EmployeeManagementSolution.sln

      - name: Build Solution
        run: msbuild EmployeeManagementSolution.sln /p:Configuration=Release
# Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build `
            -t ${{ secrets.DOCKER_USERNAME }}/employee-management:latest `
            -f EmployeeManagementProject/Dockerfile `
            .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/employee-management:latest
