name: Build Employee Management Solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore EmployeeManagementSolution.sln

      - name: Build Solution
        run: msbuild EmployeeManagementSolution.sln /p:Configuration=Release


this is my workflow now i need to add docker job in that wokflow only 
